version: '3'

services:
  web:
    container_name: subsonic
    build: .
    ports:
      - "4040:4040"
    volumes:
      - ./music:/music
      - podcast:/podcast
      - playlist:/playlist
      - subsonic:/subsonic
    restart: always

volumes:
  subsonic:
  playlist:
  podcast:
